import Text "mo:core/Text";
import Array "mo:core/Array";
import Iter "mo:core/Iter";

actor {
  type Emoji = {
    emoji : Text;
    name : Text;
    category : Text;
  };

  let emojis : [Emoji] = [
    // Smileys & Emotion
    { emoji = "😀"; name = "grinning face"; category = "Smileys & Emotion" },
    { emoji = "😁"; name = "beaming face with smiling eyes"; category = "Smileys & Emotion" },
    { emoji = "😂"; name = "face with tears of joy"; category = "Smileys & Emotion" },
    { emoji = "🤣"; name = "rolling on the floor laughing"; category = "Smileys & Emotion" },
    { emoji = "😃"; name = "grinning face with big eyes"; category = "Smileys & Emotion" },
    { emoji = "😄"; name = "grinning face with smiling eyes"; category = "Smileys & Emotion" },
    { emoji = "😅"; name = "grinning face with sweat"; category = "Smileys & Emotion" },
    { emoji = "😆"; name = "grinning squinting face"; category = "Smileys & Emotion" },
    { emoji = "😉"; name = "winking face"; category = "Smileys & Emotion" },
    { emoji = "😊"; name = "smiling face with smiling eyes"; category = "Smileys & Emotion" },
    { emoji = "😋"; name = "face savoring food"; category = "Smileys & Emotion" },
    { emoji = "😎"; name = "smiling face with sunglasses"; category = "Smileys & Emotion" },
    { emoji = "😍"; name = "smiling face with heart-eyes"; category = "Smileys & Emotion" },
    { emoji = "😘"; name = "face blowing a kiss"; category = "Smileys & Emotion" },
    { emoji = "🥰"; name = "smiling face with hearts"; category = "Smileys & Emotion" },
    { emoji = "😗"; name = "kissing face"; category = "Smileys & Emotion" },
    { emoji = "😙"; name = "kissing face with smiling eyes"; category = "Smileys & Emotion" },
    { emoji = "😚"; name = "kissing face with closed eyes"; category = "Smileys & Emotion" },
    { emoji = "😜"; name = "winking face with tongue"; category = "Smileys & Emotion" },
    { emoji = "😝"; name = "squinting face with tongue"; category = "Smileys & Emotion" },
    { emoji = "😛"; name = "face with tongue"; category = "Smileys & Emotion" },
    { emoji = "🤪"; name = "zany face"; category = "Smileys & Emotion" },
    { emoji = "🤓"; name = "nerd face"; category = "Smileys & Emotion" },
    { emoji = "🧐"; name = "face with monocle"; category = "Smileys & Emotion" },
    { emoji = "🤩"; name = "star-struck"; category = "Smileys & Emotion" },
    { emoji = "🥳"; name = "partying face"; category = "Smileys & Emotion" },
    { emoji = "😏"; name = "smirking face"; category = "Smileys & Emotion" },
    { emoji = "😒"; name = "unamused face"; category = "Smileys & Emotion" },
    { emoji = "😞"; name = "disappointed face"; category = "Smileys & Emotion" },
    { emoji = "😔"; name = "pensive face"; category = "Smileys & Emotion" },
    { emoji = "😟"; name = "worried face"; category = "Smileys & Emotion" },
    { emoji = "😕"; name = "confused face"; category = "Smileys & Emotion" },
    { emoji = "🙁"; name = "slightly frowning face"; category = "Smileys & Emotion" },
    { emoji = "☹️"; name = "frowning face"; category = "Smileys & Emotion" },
    { emoji = "😣"; name = "persevering face"; category = "Smileys & Emotion" },
    { emoji = "😖"; name = "confounded face"; category = "Smileys & Emotion" },
    { emoji = "😫"; name = "tired face"; category = "Smileys & Emotion" },
    { emoji = "😩"; name = "weary face"; category = "Smileys & Emotion" },
    { emoji = "🥺"; name = "pleading face"; category = "Smileys & Emotion" },
    { emoji = "😢"; name = "crying face"; category = "Smileys & Emotion" },
    { emoji = "😭"; name = "loudly crying face"; category = "Smileys & Emotion" },
    { emoji = "😤"; name = "face with steam from nose"; category = "Smileys & Emotion" },
    { emoji = "😠"; name = "angry face"; category = "Smileys & Emotion" },
    { emoji = "😡"; name = "pouting face"; category = "Smileys & Emotion" },
    { emoji = "🤬"; name = "face with symbols on mouth"; category = "Smileys & Emotion" },
    { emoji = "🤯"; name = "exploding head"; category = "Smileys & Emotion" },
    { emoji = "😳"; name = "flushed face"; category = "Smileys & Emotion" },
    { emoji = "🥵"; name = "hot face"; category = "Smileys & Emotion" },
    { emoji = "🥶"; name = "cold face"; category = "Smileys & Emotion" },
    { emoji = "😱"; name = "face screaming in fear"; category = "Smileys & Emotion" },
    { emoji = "😨"; name = "fearful face"; category = "Smileys & Emotion" },
    { emoji = "😰"; name = "anxious face with sweat"; category = "Smileys & Emotion" },
    { emoji = "😥"; name = "sad but relieved face"; category = "Smileys & Emotion" },
    { emoji = "😓"; name = "downcast face with sweat"; category = "Smileys & Emotion" },
    { emoji = "🤗"; name = "hugging face"; category = "Smileys & Emotion" },
    { emoji = "🤔"; name = "thinking face"; category = "Smileys & Emotion" },
    { emoji = "🤭"; name = "face with hand over mouth"; category = "Smileys & Emotion" },
    { emoji = "🤫"; name = "shushing face"; category = "Smileys & Emotion" },
    { emoji = "🤥"; name = "lying face"; category = "Smileys & Emotion" },
    { emoji = "😶"; name = "face without mouth"; category = "Smileys & Emotion" },
    { emoji = "😐"; name = "neutral face"; category = "Smileys & Emotion" },
    { emoji = "😑"; name = "expressionless face"; category = "Smileys & Emotion" },
    { emoji = "😬"; name = "grimacing face"; category = "Smileys & Emotion" },
    { emoji = "🙄"; name = "face with rolling eyes"; category = "Smileys & Emotion" },
    { emoji = "😯"; name = "hushed face"; category = "Smileys & Emotion" },
    { emoji = "😦"; name = "frowning face with open mouth"; category = "Smileys & Emotion" },
    { emoji = "😧"; name = "anguished face"; category = "Smileys & Emotion" },
    { emoji = "😮"; name = "face with open mouth"; category = "Smileys & Emotion" },
    { emoji = "😲"; name = "astonished face"; category = "Smileys & Emotion" },
    { emoji = "🥱"; name = "yawning face"; category = "Smileys & Emotion" },
    { emoji = "😴"; name = "sleeping face"; category = "Smileys & Emotion" },
    { emoji = "🤤"; name = "drooling face"; category = "Smileys & Emotion" },
    { emoji = "😪"; name = "sleepy face"; category = "Smileys & Emotion" },
    { emoji = "😵"; name = "dizzy face"; category = "Smileys & Emotion" },
    { emoji = "🤐"; name = "zipper-mouth face"; category = "Smileys & Emotion" },
    { emoji = "🥴"; name = "woozy face"; category = "Smileys & Emotion" },
    { emoji = "🤢"; name = "nauseated face"; category = "Smileys & Emotion" },
    { emoji = "🤮"; name = "face vomiting"; category = "Smileys & Emotion" },
    { emoji = "🤧"; name = "sneezing face"; category = "Smileys & Emotion" },
    { emoji = "😷"; name = "face with medical mask"; category = "Smileys & Emotion" },
    { emoji = "🤒"; name = "face with thermometer"; category = "Smileys & Emotion" },
    { emoji = "🤕"; name = "face with head-bandage"; category = "Smileys & Emotion" },
    { emoji = "🤑"; name = "money-mouth face"; category = "Smileys & Emotion" },
    { emoji = "🤠"; name = "cowboy hat face"; category = "Smileys & Emotion" },
    { emoji = "😈"; name = "smiling face with horns"; category = "Smileys & Emotion" },
    { emoji = "👿"; name = "angry face with horns"; category = "Smileys & Emotion" },
    { emoji = "👹"; name = "ogre"; category = "Smileys & Emotion" },
    { emoji = "👺"; name = "goblin"; category = "Smileys & Emotion" },
    { emoji = "💀"; name = "skull"; category = "Smileys & Emotion" },
    { emoji = "☠️"; name = "skull and crossbones"; category = "Smileys & Emotion" },
    { emoji = "👻"; name = "ghost"; category = "Smileys & Emotion" },
    { emoji = "👽"; name = "alien"; category = "Smileys & Emotion" },
    { emoji = "👾"; name = "alien monster"; category = "Smileys & Emotion" },
    { emoji = "🤖"; name = "robot"; category = "Smileys & Emotion" },
    { emoji = "😺"; name = "grinning cat"; category = "Smileys & Emotion" },
    { emoji = "😸"; name = "grinning cat with smiling eyes"; category = "Smileys & Emotion" },
    { emoji = "😹"; name = "cat with tears of joy"; category = "Smileys & Emotion" },
    { emoji = "😻"; name = "smiling cat with heart-eyes"; category = "Smileys & Emotion" },
    { emoji = "😼"; name = "cat with wry smile"; category = "Smileys & Emotion" },
    { emoji = "😽"; name = "kissing cat"; category = "Smileys & Emotion" },
    { emoji = "🙀"; name = "weary cat"; category = "Smileys & Emotion" },
    { emoji = "😿"; name = "crying cat"; category = "Smileys & Emotion" },
    { emoji = "😾"; name = "pouting cat"; category = "Smileys & Emotion" },
    { emoji = "🙈"; name = "see-no-evil monkey"; category = "Smileys & Emotion" },
    { emoji = "🙉"; name = "hear-no-evil monkey"; category = "Smileys & Emotion" },
    { emoji = "🙊"; name = "speak-no-evil monkey"; category = "Smileys & Emotion" },
    // People & Body
    { emoji = "👋"; name = "waving hand"; category = "People & Body" },
    { emoji = "🤚"; name = "raised back of hand"; category = "People & Body" },
    { emoji = "🖐️"; name = "hand with fingers splayed"; category = "People & Body" },
    { emoji = "✋"; name = "raised hand"; category = "People & Body" },
    { emoji = "🖖"; name = "vulcan salute"; category = "People & Body" },
    { emoji = "👌"; name = "ok hand"; category = "People & Body" },
    { emoji = "🤌"; name = "pinched fingers"; category = "People & Body" },
    { emoji = "🤏"; name = "pinching hand"; category = "People & Body" },
    { emoji = "✌️"; name = "victory hand"; category = "People & Body" },
    { emoji = "🤞"; name = "crossed fingers"; category = "People & Body" },
    { emoji = "🤟"; name = "love-you gesture"; category = "People & Body" },
    { emoji = "🤘"; name = "sign of the horns"; category = "People & Body" },
    { emoji = "🤙"; name = "call me hand"; category = "People & Body" },
    { emoji = "👈"; name = "backhand index pointing left"; category = "People & Body" },
    { emoji = "👉"; name = "backhand index pointing right"; category = "People & Body" },
    { emoji = "👆"; name = "backhand index pointing up"; category = "People & Body" },
    { emoji = "🖕"; name = "middle finger"; category = "People & Body" },
    { emoji = "👇"; name = "backhand index pointing down"; category = "People & Body" },
    { emoji = "☝️"; name = "index pointing up"; category = "People & Body" },
    { emoji = "👍"; name = "thumbs up"; category = "People & Body" },
    { emoji = "👎"; name = "thumbs down"; category = "People & Body" },
    { emoji = "✊"; name = "raised fist"; category = "People & Body" },
    { emoji = "👊"; name = "oncoming fist"; category = "People & Body" },
    { emoji = "🤛"; name = "left-facing fist"; category = "People & Body" },
    { emoji = "🤜"; name = "right-facing fist"; category = "People & Body" },
    { emoji = "👏"; name = "clapping hands"; category = "People & Body" },
    { emoji = "🙌"; name = "raising hands"; category = "People & Body" },
    { emoji = "👐"; name = "open hands"; category = "People & Body" },
    { emoji = "🤲"; name = "palms up together"; category = "People & Body" },
    { emoji = "🙏"; name = "folded hands"; category = "People & Body" },
    { emoji = "✍️"; name = "writing hand"; category = "People & Body" },
    { emoji = "💅"; name = "nail polish"; category = "People & Body" },
    { emoji = "🤳"; name = "selfie"; category = "People & Body" },
    { emoji = "💪"; name = "flexed biceps"; category = "People & Body" },
    { emoji = "🦾"; name = "mechanical arm"; category = "People & Body" },
    { emoji = "🦵"; name = "leg"; category = "People & Body" },
    { emoji = "🦶"; name = "foot"; category = "People & Body" },
    { emoji = "👂"; name = "ear"; category = "People & Body" },
    { emoji = "👃"; name = "nose"; category = "People & Body" },
    { emoji = "🧠"; name = "brain"; category = "People & Body" },
    { emoji = "🫀"; name = "anatomical heart"; category = "People & Body" },
    { emoji = "🫁"; name = "lungs"; category = "People & Body" },
    { emoji = "🦷"; name = "tooth"; category = "People & Body" },
    { emoji = "🦴"; name = "bone"; category = "People & Body" },
    { emoji = "👀"; name = "eyes"; category = "People & Body" },
    { emoji = "👁️"; name = "eye"; category = "People & Body" },
    { emoji = "👅"; name = "tongue"; category = "People & Body" },
    { emoji = "👄"; name = "mouth"; category = "People & Body" },
    { emoji = "💋"; name = "kiss mark"; category = "People & Body" },
    { emoji = "🫦"; name = "biting lip"; category = "People & Body" },
    { emoji = "👶"; name = "baby"; category = "People & Body" },
    { emoji = "🧒"; name = "child"; category = "People & Body" },
    { emoji = "👦"; name = "boy"; category = "People & Body" },
    { emoji = "👧"; name = "girl"; category = "People & Body" },
    { emoji = "🧑"; name = "person"; category = "People & Body" },
    { emoji = "👱"; name = "person blond hair"; category = "People & Body" },
    { emoji = "👨"; name = "man"; category = "People & Body" },
    { emoji = "🧔"; name = "person beard"; category = "People & Body" },
    { emoji = "👩"; name = "woman"; category = "People & Body" },
    { emoji = "🧓"; name = "older person"; category = "People & Body" },
    { emoji = "👴"; name = "old man"; category = "People & Body" },
    { emoji = "👵"; name = "old woman"; category = "People & Body" },
    { emoji = "🙍"; name = "person frowning"; category = "People & Body" },
    { emoji = "🙎"; name = "person pouting"; category = "People & Body" },
    { emoji = "🙅"; name = "person gesturing no"; category = "People & Body" },
    { emoji = "🙆"; name = "person gesturing ok"; category = "People & Body" },
    { emoji = "💁"; name = "person tipping hand"; category = "People & Body" },
    { emoji = "🙋"; name = "person raising hand"; category = "People & Body" },
    { emoji = "🧏"; name = "deaf person"; category = "People & Body" },
    { emoji = "🙇"; name = "person bowing"; category = "People & Body" },
    { emoji = "🤦"; name = "person facepalming"; category = "People & Body" },
    { emoji = "🤷"; name = "person shrugging"; category = "People & Body" },
    { emoji = "💆"; name = "person getting massage"; category = "People & Body" },
    { emoji = "💇"; name = "person getting haircut"; category = "People & Body" },
    { emoji = "🚶"; name = "person walking"; category = "People & Body" },
    { emoji = "🧍"; name = "person standing"; category = "People & Body" },
    { emoji = "🧎"; name = "person kneeling"; category = "People & Body" },
    { emoji = "🏃"; name = "person running"; category = "People & Body" },
    { emoji = "💃"; name = "woman dancing"; category = "People & Body" },
    { emoji = "🕺"; name = "man dancing"; category = "People & Body" },
    { emoji = "🧖"; name = "person in steamy room"; category = "People & Body" },
    { emoji = "🧗"; name = "person climbing"; category = "People & Body" },
    { emoji = "🏇"; name = "horse racing"; category = "People & Body" },
    { emoji = "🏂"; name = "snowboarder"; category = "People & Body" },
    { emoji = "🏋️"; name = "person lifting weights"; category = "People & Body" },
    { emoji = "🤼"; name = "people wrestling"; category = "People & Body" },
    { emoji = "🤸"; name = "person cartwheeling"; category = "People & Body" },
    { emoji = "🤾"; name = "person playing handball"; category = "People & Body" },
    { emoji = "🧘"; name = "person in lotus position"; category = "People & Body" },
    { emoji = "🛀"; name = "person taking bath"; category = "People & Body" },
    { emoji = "🛌"; name = "person in bed"; category = "People & Body" },
    { emoji = "🤝"; name = "people holding hands"; category = "People & Body" },
    { emoji = "👫"; name = "woman and man holding hands"; category = "People & Body" },
    { emoji = "👬"; name = "men holding hands"; category = "People & Body" },
    { emoji = "👭"; name = "women holding hands"; category = "People & Body" },
    { emoji = "💏"; name = "kiss"; category = "People & Body" },
    { emoji = "💑"; name = "couple with heart"; category = "People & Body" },
    { emoji = "👨‍👩‍👦"; name = "family"; category = "People & Body" },
    { emoji = "🗣️"; name = "speaking head"; category = "People & Body" },
    { emoji = "👤"; name = "bust in silhouette"; category = "People & Body" },
    { emoji = "👥"; name = "busts in silhouette"; category = "People & Body" },
    // Animals & Nature
    { emoji = "🐶"; name = "dog face"; category = "Animals & Nature" },
    { emoji = "🐱"; name = "cat face"; category = "Animals & Nature" },
    { emoji = "🐭"; name = "mouse face"; category = "Animals & Nature" },
    { emoji = "🐹"; name = "hamster face"; category = "Animals & Nature" },
    { emoji = "🐰"; name = "rabbit face"; category = "Animals & Nature" },
    { emoji = "🦊"; name = "fox face"; category = "Animals & Nature" },
    { emoji = "🐻"; name = "bear face"; category = "Animals & Nature" },
    { emoji = "🐼"; name = "panda face"; category = "Animals & Nature" },
    { emoji = "🐨"; name = "koala"; category = "Animals & Nature" },
    { emoji = "🐯"; name = "tiger face"; category = "Animals & Nature" },
    { emoji = "🦁"; name = "lion face"; category = "Animals & Nature" },
    { emoji = "🐮"; name = "cow face"; category = "Animals & Nature" },
    { emoji = "🐷"; name = "pig face"; category = "Animals & Nature" },
    { emoji = "🐸"; name = "frog face"; category = "Animals & Nature" },
    { emoji = "🐵"; name = "monkey face"; category = "Animals & Nature" },
    { emoji = "🙈"; name = "see-no-evil monkey"; category = "Animals & Nature" },
    { emoji = "🐔"; name = "chicken"; category = "Animals & Nature" },
    { emoji = "🐧"; name = "penguin"; category = "Animals & Nature" },
    { emoji = "🐦"; name = "bird"; category = "Animals & Nature" },
    { emoji = "🐤"; name = "baby chick"; category = "Animals & Nature" },
    { emoji = "🦆"; name = "duck"; category = "Animals & Nature" },
    { emoji = "🦅"; name = "eagle"; category = "Animals & Nature" },
    { emoji = "🦉"; name = "owl"; category = "Animals & Nature" },
    { emoji = "🦇"; name = "bat"; category = "Animals & Nature" },
    { emoji = "🐺"; name = "wolf face"; category = "Animals & Nature" },
    { emoji = "🐗"; name = "boar"; category = "Animals & Nature" },
    { emoji = "🐴"; name = "horse face"; category = "Animals & Nature" },
    { emoji = "🦄"; name = "unicorn face"; category = "Animals & Nature" },
    { emoji = "🐝"; name = "honeybee"; category = "Animals & Nature" },
    { emoji = "🐛"; name = "bug"; category = "Animals & Nature" },
    { emoji = "🦋"; name = "butterfly"; category = "Animals & Nature" },
    { emoji = "🐌"; name = "snail"; category = "Animals & Nature" },
    { emoji = "🐞"; name = "ladybug"; category = "Animals & Nature" },
    { emoji = "🐜"; name = "ant"; category = "Animals & Nature" },
    { emoji = "🦟"; name = "mosquito"; category = "Animals & Nature" },
    { emoji = "🦗"; name = "cricket"; category = "Animals & Nature" },
    { emoji = "🕷️"; name = "spider"; category = "Animals & Nature" },
    { emoji = "🦂"; name = "scorpion"; category = "Animals & Nature" },
    { emoji = "🐢"; name = "turtle"; category = "Animals & Nature" },
    { emoji = "🐍"; name = "snake"; category = "Animals & Nature" },
    { emoji = "🦎"; name = "lizard"; category = "Animals & Nature" },
    { emoji = "🦖"; name = "t-rex"; category = "Animals & Nature" },
    { emoji = "🦕"; name = "sauropod"; category = "Animals & Nature" },
    { emoji = "🐊"; name = "crocodile"; category = "Animals & Nature" },
    { emoji = "🐸"; name = "frog"; category = "Animals & Nature" },
    { emoji = "🐲"; name = "dragon face"; category = "Animals & Nature" },
    { emoji = "🌵"; name = "cactus"; category = "Animals & Nature" },
    { emoji = "🎄"; name = "christmas tree"; category = "Animals & Nature" },
    { emoji = "🌲"; name = "evergreen tree"; category = "Animals & Nature" },
    { emoji = "🌳"; name = "deciduous tree"; category = "Animals & Nature" },
    { emoji = "🌴"; name = "palm tree"; category = "Animals & Nature" },
    { emoji = "🌿"; name = "herb"; category = "Animals & Nature" },
    { emoji = "☘️"; name = "shamrock"; category = "Animals & Nature" },
    { emoji = "🍀"; name = "four leaf clover"; category = "Animals & Nature" },
    { emoji = "🎋"; name = "tanabata tree"; category = "Animals & Nature" },
    { emoji = "🎍"; name = "pine decoration"; category = "Animals & Nature" },
    { emoji = "🍃"; name = "leaf fluttering in wind"; category = "Animals & Nature" },
    { emoji = "🍂"; name = "fallen leaf"; category = "Animals & Nature" },
    { emoji = "🍁"; name = "maple leaf"; category = "Animals & Nature" },
    { emoji = "🌾"; name = "sheaf of rice"; category = "Animals & Nature" },
    { emoji = "🌺"; name = "hibiscus"; category = "Animals & Nature" },
    { emoji = "🌸"; name = "cherry blossom"; category = "Animals & Nature" },
    { emoji = "🌼"; name = "blossom"; category = "Animals & Nature" },
    { emoji = "🌻"; name = "sunflower"; category = "Animals & Nature" },
    { emoji = "🌹"; name = "rose"; category = "Animals & Nature" },
    { emoji = "🥀"; name = "wilted flower"; category = "Animals & Nature" },
    { emoji = "🌷"; name = "tulip"; category = "Animals & Nature" },
    { emoji = "🌱"; name = "seedling"; category = "Animals & Nature" },
    { emoji = "🌲"; name = "evergreen"; category = "Animals & Nature" },
    { emoji = "🍄"; name = "mushroom"; category = "Animals & Nature" },
    { emoji = "🐚"; name = "spiral shell"; category = "Animals & Nature" },
    { emoji = "🪸"; name = "coral"; category = "Animals & Nature" },
    { emoji = "🐠"; name = "tropical fish"; category = "Animals & Nature" },
    { emoji = "🐟"; name = "fish"; category = "Animals & Nature" },
    { emoji = "🐡"; name = "blowfish"; category = "Animals & Nature" },
    { emoji = "🐬"; name = "dolphin"; category = "Animals & Nature" },
    { emoji = "🦭"; name = "seal"; category = "Animals & Nature" },
    { emoji = "🐳"; name = "spouting whale"; category = "Animals & Nature" },
    { emoji = "🦈"; name = "shark"; category = "Animals & Nature" },
    { emoji = "🐙"; name = "octopus"; category = "Animals & Nature" },
    { emoji = "🦑"; name = "squid"; category = "Animals & Nature" },
    { emoji = "🦐"; name = "shrimp"; category = "Animals & Nature" },
    { emoji = "🦀"; name = "crab"; category = "Animals & Nature" },
    { emoji = "🦞"; name = "lobster"; category = "Animals & Nature" },
    { emoji = "🐡"; name = "puffer fish"; category = "Animals & Nature" },
    { emoji = "🐓"; name = "rooster"; category = "Animals & Nature" },
    { emoji = "🦃"; name = "turkey"; category = "Animals & Nature" },
    { emoji = "🦚"; name = "peacock"; category = "Animals & Nature" },
    { emoji = "🦜"; name = "parrot"; category = "Animals & Nature" },
    { emoji = "🦢"; name = "swan"; category = "Animals & Nature" },
    { emoji = "🦩"; name = "flamingo"; category = "Animals & Nature" },
    { emoji = "🐕"; name = "dog"; category = "Animals & Nature" },
    { emoji = "🐩"; name = "poodle"; category = "Animals & Nature" },
    { emoji = "🦮"; name = "guide dog"; category = "Animals & Nature" },
    { emoji = "🐈"; name = "cat"; category = "Animals & Nature" },
    { emoji = "🐈"; name = "black cat"; category = "Animals & Nature" },
    { emoji = "🐇"; name = "rabbit"; category = "Animals & Nature" },
    { emoji = "🐁"; name = "mouse"; category = "Animals & Nature" },
    { emoji = "🐿️"; name = "chipmunk"; category = "Animals & Nature" },
    { emoji = "🦔"; name = "hedgehog"; category = "Animals & Nature" },
    { emoji = "🐾"; name = "paw prints"; category = "Animals & Nature" },
    // Food & Drink
    { emoji = "🍎"; name = "red apple"; category = "Food & Drink" },
    { emoji = "🍊"; name = "tangerine"; category = "Food & Drink" },
    { emoji = "🍋"; name = "lemon"; category = "Food & Drink" },
    { emoji = "🍌"; name = "banana"; category = "Food & Drink" },
    { emoji = "🍉"; name = "watermelon"; category = "Food & Drink" },
    { emoji = "🍇"; name = "grapes"; category = "Food & Drink" },
    { emoji = "🍓"; name = "strawberry"; category = "Food & Drink" },
    { emoji = "🫐"; name = "blueberries"; category = "Food & Drink" },
    { emoji = "🍈"; name = "melon"; category = "Food & Drink" },
    { emoji = "🍒"; name = "cherries"; category = "Food & Drink" },
    { emoji = "🍑"; name = "peach"; category = "Food & Drink" },
    { emoji = "🥭"; name = "mango"; category = "Food & Drink" },
    { emoji = "🍍"; name = "pineapple"; category = "Food & Drink" },
    { emoji = "🥥"; name = "coconut"; category = "Food & Drink" },
    { emoji = "🥝"; name = "kiwi fruit"; category = "Food & Drink" },
    { emoji = "🍅"; name = "tomato"; category = "Food & Drink" },
    { emoji = "🍆"; name = "eggplant"; category = "Food & Drink" },
    { emoji = "🥑"; name = "avocado"; category = "Food & Drink" },
    { emoji = "🥦"; name = "broccoli"; category = "Food & Drink" },
    { emoji = "🥬"; name = "leafy green"; category = "Food & Drink" },
    { emoji = "🥒"; name = "cucumber"; category = "Food & Drink" },
    { emoji = "🌶️"; name = "hot pepper"; category = "Food & Drink" },
    { emoji = "🫑"; name = "bell pepper"; category = "Food & Drink" },
    { emoji = "🌽"; name = "ear of corn"; category = "Food & Drink" },
    { emoji = "🥕"; name = "carrot"; category = "Food & Drink" },
    { emoji = "🧄"; name = "garlic"; category = "Food & Drink" },
    { emoji = "🧅"; name = "onion"; category = "Food & Drink" },
    { emoji = "🥔"; name = "potato"; category = "Food & Drink" },
    { emoji = "🍠"; name = "roasted sweet potato"; category = "Food & Drink" },
    { emoji = "🥐"; name = "croissant"; category = "Food & Drink" },
    { emoji = "🥖"; name = "baguette bread"; category = "Food & Drink" },
    { emoji = "🍞"; name = "bread"; category = "Food & Drink" },
    { emoji = "🥨"; name = "pretzel"; category = "Food & Drink" },
    { emoji = "🥯"; name = "bagel"; category = "Food & Drink" },
    { emoji = "🧀"; name = "cheese wedge"; category = "Food & Drink" },
    { emoji = "🥚"; name = "egg"; category = "Food & Drink" },
    { emoji = "🍳"; name = "cooking"; category = "Food & Drink" },
    { emoji = "🥞"; name = "pancakes"; category = "Food & Drink" },
    { emoji = "🧇"; name = "waffle"; category = "Food & Drink" },
    { emoji = "🥓"; name = "bacon"; category = "Food & Drink" },
    { emoji = "🥩"; name = "cut of meat"; category = "Food & Drink" },
    { emoji = "🍗"; name = "poultry leg"; category = "Food & Drink" },
    { emoji = "🍖"; name = "meat on bone"; category = "Food & Drink" },
    { emoji = "🦴"; name = "bone"; category = "Food & Drink" },
    { emoji = "🍔"; name = "hamburger"; category = "Food & Drink" },
    { emoji = "🍟"; name = "french fries"; category = "Food & Drink" },
    { emoji = "🍕"; name = "pizza"; category = "Food & Drink" },
    { emoji = "🌭"; name = "hot dog"; category = "Food & Drink" },
    { emoji = "🥪"; name = "sandwich"; category = "Food & Drink" },
    { emoji = "🌮"; name = "taco"; category = "Food & Drink" },
    { emoji = "🌯"; name = "burrito"; category = "Food & Drink" },
    { emoji = "🫔"; name = "tamale"; category = "Food & Drink" },
    { emoji = "🥙"; name = "stuffed flatbread"; category = "Food & Drink" },
    { emoji = "🧆"; name = "falafel"; category = "Food & Drink" },
    { emoji = "🥚"; name = "egg"; category = "Food & Drink" },
    { emoji = "🍱"; name = "bento box"; category = "Food & Drink" },
    { emoji = "🍘"; name = "rice cracker"; category = "Food & Drink" },
    { emoji = "🍙"; name = "rice ball"; category = "Food & Drink" },
    { emoji = "🍚"; name = "cooked rice"; category = "Food & Drink" },
    { emoji = "🍛"; name = "curry rice"; category = "Food & Drink" },
    { emoji = "🍜"; name = "steaming bowl"; category = "Food & Drink" },
    { emoji = "🍝"; name = "spaghetti"; category = "Food & Drink" },
    { emoji = "🍠"; name = "sweet potato"; category = "Food & Drink" },
    { emoji = "🍢"; name = "oden"; category = "Food & Drink" },
    { emoji = "🍣"; name = "sushi"; category = "Food & Drink" },
    { emoji = "🍤"; name = "fried shrimp"; category = "Food & Drink" },
    { emoji = "🍥"; name = "fish cake"; category = "Food & Drink" },
    { emoji = "🥮"; name = "moon cake"; category = "Food & Drink" },
    { emoji = "🍡"; name = "dango"; category = "Food & Drink" },
    { emoji = "🥟"; name = "dumpling"; category = "Food & Drink" },
    { emoji = "🥠"; name = "fortune cookie"; category = "Food & Drink" },
    { emoji = "🥡"; name = "takeout box"; category = "Food & Drink" },
    { emoji = "🦪"; name = "oyster"; category = "Food & Drink" },
    { emoji = "🍦"; name = "soft ice cream"; category = "Food & Drink" },
    { emoji = "🍧"; name = "shaved ice"; category = "Food & Drink" },
    { emoji = "🍨"; name = "ice cream"; category = "Food & Drink" },
    { emoji = "🍩"; name = "doughnut"; category = "Food & Drink" },
    { emoji = "🍪"; name = "cookie"; category = "Food & Drink" },
    { emoji = "🎂"; name = "birthday cake"; category = "Food & Drink" },
    { emoji = "🍰"; name = "shortcake"; category = "Food & Drink" },
    { emoji = "🧁"; name = "cupcake"; category = "Food & Drink" },
    { emoji = "🥧"; name = "pie"; category = "Food & Drink" },
    { emoji = "🍫"; name = "chocolate bar"; category = "Food & Drink" },
    { emoji = "🍬"; name = "candy"; category = "Food & Drink" },
    { emoji = "🍭"; name = "lollipop"; category = "Food & Drink" },
    { emoji = "🍮"; name = "custard"; category = "Food & Drink" },
    { emoji = "🍯"; name = "honey pot"; category = "Food & Drink" },
    { emoji = "🍼"; name = "baby bottle"; category = "Food & Drink" },
    { emoji = "🥛"; name = "glass of milk"; category = "Food & Drink" },
    { emoji = "☕"; name = "hot beverage"; category = "Food & Drink" },
    { emoji = "🫖"; name = "teapot"; category = "Food & Drink" },
    { emoji = "🍵"; name = "teacup without handle"; category = "Food & Drink" },
    { emoji = "🧃"; name = "beverage box"; category = "Food & Drink" },
    { emoji = "🥤"; name = "cup with straw"; category = "Food & Drink" },
    { emoji = "🧋"; name = "bubble tea"; category = "Food & Drink" },
    { emoji = "🍶"; name = "sake"; category = "Food & Drink" },
    { emoji = "🍺"; name = "beer mug"; category = "Food & Drink" },
    { emoji = "🍻"; name = "clinking beer mugs"; category = "Food & Drink" },
    { emoji = "🥂"; name = "clinking glasses"; category = "Food & Drink" },
    { emoji = "🍷"; name = "wine glass"; category = "Food & Drink" },
    { emoji = "🥃"; name = "tumbler glass"; category = "Food & Drink" },
    { emoji = "🍸"; name = "cocktail glass"; category = "Food & Drink" },
    { emoji = "🍹"; name = "tropical drink"; category = "Food & Drink" },
    { emoji = "🧉"; name = "mate"; category = "Food & Drink" },
    { emoji = "🍾"; name = "bottle with popping cork"; category = "Food & Drink" },
    { emoji = "🧊"; name = "ice"; category = "Food & Drink" },
    // Travel & Places
    { emoji = "🚗"; name = "car"; category = "Travel & Places" },
    { emoji = "🚕"; name = "taxi"; category = "Travel & Places" },
    { emoji = "🚙"; name = "sport utility vehicle"; category = "Travel & Places" },
    { emoji = "🚌"; name = "bus"; category = "Travel & Places" },
    { emoji = "🚎"; name = "trolleybus"; category = "Travel & Places" },
    { emoji = "🏎️"; name = "racing car"; category = "Travel & Places" },
    { emoji = "🚓"; name = "police car"; category = "Travel & Places" },
    { emoji = "🚑"; name = "ambulance"; category = "Travel & Places" },
    { emoji = "🚒"; name = "fire engine"; category = "Travel & Places" },
    { emoji = "🚐"; name = "minibus"; category = "Travel & Places" },
    { emoji = "🚚"; name = "delivery truck"; category = "Travel & Places" },
    { emoji = "🚛"; name = "articulated lorry"; category = "Travel & Places" },
    { emoji = "🚜"; name = "tractor"; category = "Travel & Places" },
    { emoji = "🏗️"; name = "building construction"; category = "Travel & Places" },
    { emoji = "🚲"; name = "bicycle"; category = "Travel & Places" },
    { emoji = "🛴"; name = "kick scooter"; category = "Travel & Places" },
    { emoji = "🛵"; name = "motor scooter"; category = "Travel & Places" },
    { emoji = "🏍️"; name = "motorcycle"; category = "Travel & Places" },
    { emoji = "✈️"; name = "airplane"; category = "Travel & Places" },
    { emoji = "🛩️"; name = "small airplane"; category = "Travel & Places" },
    { emoji = "🚀"; name = "rocket"; category = "Travel & Places" },
    { emoji = "🛸"; name = "flying saucer"; category = "Travel & Places" },
    { emoji = "🚁"; name = "helicopter"; category = "Travel & Places" },
    { emoji = "🛶"; name = "canoe"; category = "Travel & Places" },
    { emoji = "⛵"; name = "sailboat"; category = "Travel & Places" },
    { emoji = "🚤"; name = "speedboat"; category = "Travel & Places" },
    { emoji = "🛥️"; name = "motor boat"; category = "Travel & Places" },
    { emoji = "🚢"; name = "ship"; category = "Travel & Places" },
    { emoji = "⛽"; name = "fuel pump"; category = "Travel & Places" },
    { emoji = "🚦"; name = "vertical traffic light"; category = "Travel & Places" },
    { emoji = "🚥"; name = "horizontal traffic light"; category = "Travel & Places" },
    { emoji = "🚧"; name = "construction"; category = "Travel & Places" },
    { emoji = "⚓"; name = "anchor"; category = "Travel & Places" },
    { emoji = "🛤️"; name = "railway track"; category = "Travel & Places" },
    { emoji = "🛣️"; name = "motorway"; category = "Travel & Places" },
    { emoji = "🗺️"; name = "world map"; category = "Travel & Places" },
    { emoji = "🗾"; name = "map of japan"; category = "Travel & Places" },
    { emoji = "🧭"; name = "compass"; category = "Travel & Places" },
    { emoji = "⛰️"; name = "mountain"; category = "Travel & Places" },
    { emoji = "🏔️"; name = "snow-capped mountain"; category = "Travel & Places" },
    { emoji = "🌋"; name = "volcano"; category = "Travel & Places" },
    { emoji = "🗻"; name = "mount fuji"; category = "Travel & Places" },
    { emoji = "🏕️"; name = "camping"; category = "Travel & Places" },
    { emoji = "🏖️"; name = "beach with umbrella"; category = "Travel & Places" },
    { emoji = "🏜️"; name = "desert"; category = "Travel & Places" },
    { emoji = "🏝️"; name = "desert island"; category = "Travel & Places" },
    { emoji = "🏞️"; name = "national park"; category = "Travel & Places" },
    { emoji = "🏟️"; name = "stadium"; category = "Travel & Places" },
    { emoji = "🏛️"; name = "classical building"; category = "Travel & Places" },
    { emoji = "🏗️"; name = "construction"; category = "Travel & Places" },
    { emoji = "🏘️"; name = "houses"; category = "Travel & Places" },
    { emoji = "🏚️"; name = "derelict house"; category = "Travel & Places" },
    { emoji = "🏠"; name = "house"; category = "Travel & Places" },
    { emoji = "🏡"; name = "house with garden"; category = "Travel & Places" },
    { emoji = "🏢"; name = "office building"; category = "Travel & Places" },
    { emoji = "🏣"; name = "japanese post office"; category = "Travel & Places" },
    { emoji = "🏥"; name = "hospital"; category = "Travel & Places" },
    { emoji = "🏦"; name = "bank"; category = "Travel & Places" },
    { emoji = "🏧"; name = "atm sign"; category = "Travel & Places" },
    { emoji = "🏨"; name = "hotel"; category = "Travel & Places" },
    { emoji = "🏩"; name = "love hotel"; category = "Travel & Places" },
    { emoji = "🏪"; name = "convenience store"; category = "Travel & Places" },
    { emoji = "🏫"; name = "school"; category = "Travel & Places" },
    { emoji = "🏬"; name = "department store"; category = "Travel & Places" },
    { emoji = "🏭"; name = "factory"; category = "Travel & Places" },
    { emoji = "🏯"; name = "japanese castle"; category = "Travel & Places" },
    { emoji = "🏰"; name = "castle"; category = "Travel & Places" },
    { emoji = "💒"; name = "wedding"; category = "Travel & Places" },
    { emoji = "🗼"; name = "tokyo tower"; category = "Travel & Places" },
    { emoji = "🗽"; name = "statue of liberty"; category = "Travel & Places" },
    { emoji = "⛪"; name = "church"; category = "Travel & Places" },
    { emoji = "🕌"; name = "mosque"; category = "Travel & Places" },
    { emoji = "🛕"; name = "hindu temple"; category = "Travel & Places" },
    { emoji = "🕍"; name = "synagogue"; category = "Travel & Places" },
    { emoji = "⛩️"; name = "shinto shrine"; category = "Travel & Places" },
    { emoji = "🕋"; name = "kaaba"; category = "Travel & Places" },
    { emoji = "⛲"; name = "fountain"; category = "Travel & Places" },
    { emoji = "⛺"; name = "tent"; category = "Travel & Places" },
    { emoji = "🌁"; name = "foggy"; category = "Travel & Places" },
    { emoji = "🌃"; name = "night with stars"; category = "Travel & Places" },
    { emoji = "🌄"; name = "sunrise over mountains"; category = "Travel & Places" },
    { emoji = "🌅"; name = "sunrise"; category = "Travel & Places" },
    { emoji = "🌆"; name = "cityscape at dusk"; category = "Travel & Places" },
    { emoji = "🌇"; name = "sunset"; category = "Travel & Places" },
    { emoji = "🌉"; name = "bridge at night"; category = "Travel & Places" },
    { emoji = "🌌"; name = "milky way"; category = "Travel & Places" },
    { emoji = "🌠"; name = "shooting star"; category = "Travel & Places" },
    { emoji = "🎆"; name = "fireworks"; category = "Travel & Places" },
    { emoji = "🎇"; name = "sparkler"; category = "Travel & Places" },
    { emoji = "🗓️"; name = "spiral calendar"; category = "Travel & Places" },
    // Activities & Sports
    { emoji = "⚽"; name = "soccer ball"; category = "Activities & Sports" },
    { emoji = "🏀"; name = "basketball"; category = "Activities & Sports" },
    { emoji = "🏈"; name = "american football"; category = "Activities & Sports" },
    { emoji = "⚾"; name = "baseball"; category = "Activities & Sports" },
    { emoji = "🥎"; name = "softball"; category = "Activities & Sports" },
    { emoji = "🏐"; name = "volleyball"; category = "Activities & Sports" },
    { emoji = "🏉"; name = "rugby football"; category = "Activities & Sports" },
    { emoji = "🎾"; name = "tennis"; category = "Activities & Sports" },
    { emoji = "🥏"; name = "flying disc"; category = "Activities & Sports" },
    { emoji = "🎳"; name = "bowling"; category = "Activities & Sports" },
    { emoji = "🏏"; name = "cricket game"; category = "Activities & Sports" },
    { emoji = "🏑"; name = "field hockey"; category = "Activities & Sports" },
    { emoji = "🏒"; name = "ice hockey"; category = "Activities & Sports" },
    { emoji = "🥍"; name = "lacrosse"; category = "Activities & Sports" },
    { emoji = "🏓"; name = "ping pong"; category = "Activities & Sports" },
    { emoji = "🏸"; name = "badminton"; category = "Activities & Sports" },
    { emoji = "🥊"; name = "boxing glove"; category = "Activities & Sports" },
    { emoji = "🥋"; name = "martial arts uniform"; category = "Activities & Sports" },
    { emoji = "🥅"; name = "goal net"; category = "Activities & Sports" },
    { emoji = "⛳"; name = "flag in hole"; category = "Activities & Sports" },
    { emoji = "⛸️"; name = "ice skate"; category = "Activities & Sports" },
    { emoji = "🎣"; name = "fishing pole"; category = "Activities & Sports" },
    { emoji = "🤿"; name = "diving mask"; category = "Activities & Sports" },
    { emoji = "🎽"; name = "running shirt"; category = "Activities & Sports" },
    { emoji = "🎿"; name = "skis"; category = "Activities & Sports" },
    { emoji = "🛷"; name = "sled"; category = "Activities & Sports" },
    { emoji = "🥌"; name = "curling stone"; category = "Activities & Sports" },
    { emoji = "🎯"; name = "bullseye"; category = "Activities & Sports" },
    { emoji = "🪀"; name = "yo-yo"; category = "Activities & Sports" },
    { emoji = "🪁"; name = "slingshot"; category = "Activities & Sports" },
    { emoji = "🎱"; name = "pool 8 ball"; category = "Activities & Sports" },
    { emoji = "🔮"; name = "crystal ball"; category = "Activities & Sports" },
    { emoji = "🪄"; name = "magic wand"; category = "Activities & Sports" },
    { emoji = "🎮"; name = "video game"; category = "Activities & Sports" },
    { emoji = "🕹️"; name = "joystick"; category = "Activities & Sports" },
    { emoji = "🎲"; name = "game die"; category = "Activities & Sports" },
    { emoji = "♟️"; name = "chess pawn"; category = "Activities & Sports" },
    { emoji = "🎭"; name = "performing arts"; category = "Activities & Sports" },
    { emoji = "🎨"; name = "artist palette"; category = "Activities & Sports" },
    { emoji = "🧵"; name = "thread"; category = "Activities & Sports" },
    { emoji = "🧶"; name = "yarn"; category = "Activities & Sports" },
    { emoji = "🎪"; name = "circus tent"; category = "Activities & Sports" },
    { emoji = "🎠"; name = "carousel horse"; category = "Activities & Sports" },
    { emoji = "🎡"; name = "ferris wheel"; category = "Activities & Sports" },
    { emoji = "🎢"; name = "roller coaster"; category = "Activities & Sports" },
    { emoji = "🎫"; name = "ticket"; category = "Activities & Sports" },
    { emoji = "🎟️"; name = "admission tickets"; category = "Activities & Sports" },
    { emoji = "🎖️"; name = "military medal"; category = "Activities & Sports" },
    { emoji = "🏆"; name = "trophy"; category = "Activities & Sports" },
    { emoji = "🥇"; name = "1st place medal"; category = "Activities & Sports" },
    { emoji = "🥈"; name = "2nd place medal"; category = "Activities & Sports" },
    { emoji = "🥉"; name = "3rd place medal"; category = "Activities & Sports" },
    { emoji = "🏅"; name = "sports medal"; category = "Activities & Sports" },
    { emoji = "🎗️"; name = "reminder ribbon"; category = "Activities & Sports" },
    { emoji = "🎀"; name = "ribbon"; category = "Activities & Sports" },
    { emoji = "🎁"; name = "wrapped gift"; category = "Activities & Sports" },
    { emoji = "🎈"; name = "balloon"; category = "Activities & Sports" },
    { emoji = "🎉"; name = "party popper"; category = "Activities & Sports" },
    { emoji = "🎊"; name = "confetti ball"; category = "Activities & Sports" },
    { emoji = "🎋"; name = "tanabata tree"; category = "Activities & Sports" },
    { emoji = "🎍"; name = "pine decoration"; category = "Activities & Sports" },
    { emoji = "🎎"; name = "japanese dolls"; category = "Activities & Sports" },
    { emoji = "🎏"; name = "carp streamer"; category = "Activities & Sports" },
    { emoji = "🎐"; name = "wind chime"; category = "Activities & Sports" },
    { emoji = "🎑"; name = "moon viewing ceremony"; category = "Activities & Sports" },
    { emoji = "🧧"; name = "red envelope"; category = "Activities & Sports" },
    { emoji = "🎃"; name = "jack-o-lantern"; category = "Activities & Sports" },
    { emoji = "🎄"; name = "christmas tree"; category = "Activities & Sports" },
    { emoji = "🎆"; name = "fireworks"; category = "Activities & Sports" },
    { emoji = "🎇"; name = "sparkler"; category = "Activities & Sports" },
    { emoji = "🧨"; name = "firecracker"; category = "Activities & Sports" },
    { emoji = "✨"; name = "sparkles"; category = "Activities & Sports" },
    { emoji = "🎴"; name = "flower playing cards"; category = "Activities & Sports" },
    { emoji = "🀄"; name = "mahjong red dragon"; category = "Activities & Sports" },
    { emoji = "🃏"; name = "joker"; category = "Activities & Sports" },
    { emoji = "🎰"; name = "slot machine"; category = "Activities & Sports" },
    // Objects
    { emoji = "⌚"; name = "watch"; category = "Objects" },
    { emoji = "📱"; name = "mobile phone"; category = "Objects" },
    { emoji = "📲"; name = "mobile phone with arrow"; category = "Objects" },
    { emoji = "💻"; name = "laptop"; category = "Objects" },
    { emoji = "⌨️"; name = "keyboard"; category = "Objects" },
    { emoji = "🖥️"; name = "desktop computer"; category = "Objects" },
    { emoji = "🖨️"; name = "printer"; category = "Objects" },
    { emoji = "🖱️"; name = "computer mouse"; category = "Objects" },
    { emoji = "🖲️"; name = "trackball"; category = "Objects" },
    { emoji = "💽"; name = "computer disk"; category = "Objects" },
    { emoji = "💾"; name = "floppy disk"; category = "Objects" },
    { emoji = "💿"; name = "optical disk"; category = "Objects" },
    { emoji = "📀"; name = "dvd"; category = "Objects" },
    { emoji = "🧮"; name = "abacus"; category = "Objects" },
    { emoji = "📷"; name = "camera"; category = "Objects" },
    { emoji = "📸"; name = "camera with flash"; category = "Objects" },
    { emoji = "📹"; name = "video camera"; category = "Objects" },
    { emoji = "🎥"; name = "movie camera"; category = "Objects" },
    { emoji = "📽️"; name = "film projector"; category = "Objects" },
    { emoji = "🎞️"; name = "film frames"; category = "Objects" },
    { emoji = "📞"; name = "telephone receiver"; category = "Objects" },
    { emoji = "☎️"; name = "telephone"; category = "Objects" },
    { emoji = "📟"; name = "pager"; category = "Objects" },
    { emoji = "📠"; name = "fax machine"; category = "Objects" },
    { emoji = "📺"; name = "television"; category = "Objects" },
    { emoji = "📻"; name = "radio"; category = "Objects" },
    { emoji = "🧭"; name = "compass"; category = "Objects" },
    { emoji = "⏱️"; name = "stopwatch"; category = "Objects" },
    { emoji = "⏲️"; name = "timer clock"; category = "Objects" },
    { emoji = "⏰"; name = "alarm clock"; category = "Objects" },
    { emoji = "🕰️"; name = "mantelpiece clock"; category = "Objects" },
    { emoji = "⌛"; name = "hourglass done"; category = "Objects" },
    { emoji = "⏳"; name = "hourglass not done"; category = "Objects" },
    { emoji = "📡"; name = "satellite antenna"; category = "Objects" },
    { emoji = "🔋"; name = "battery"; category = "Objects" },
    { emoji = "🪫"; name = "low battery"; category = "Objects" },
    { emoji = "🔌"; name = "electric plug"; category = "Objects" },
    { emoji = "💡"; name = "light bulb"; category = "Objects" },
    { emoji = "🔦"; name = "flashlight"; category = "Objects" },
    { emoji = "🕯️"; name = "candle"; category = "Objects" },
    { emoji = "🧱"; name = "brick"; category = "Objects" },
    { emoji = "💎"; name = "gem stone"; category = "Objects" },
    { emoji = "🔧"; name = "wrench"; category = "Objects" },
    { emoji = "🪛"; name = "screwdriver"; category = "Objects" },
    { emoji = "🔨"; name = "hammer"; category = "Objects" },
    { emoji = "⚒️"; name = "hammer and pick"; category = "Objects" },
    { emoji = "🛠️"; name = "hammer and wrench"; category = "Objects" },
    { emoji = "⛏️"; name = "pick"; category = "Objects" },
    { emoji = "🪚"; name = "carpentry saw"; category = "Objects" },
    { emoji = "🔩"; name = "nut and bolt"; category = "Objects" },
    { emoji = "🪤"; name = "mouse trap"; category = "Objects" },
    { emoji = "🔗"; name = "link"; category = "Objects" },
    { emoji = "⛓️"; name = "chains"; category = "Objects" },
    { emoji = "🪝"; name = "hook"; category = "Objects" },
    { emoji = "🧲"; name = "magnet"; category = "Objects" },
    { emoji = "🔑"; name = "key"; category = "Objects" },
    { emoji = "🗝️"; name = "old key"; category = "Objects" },
    { emoji = "🔒"; name = "locked"; category = "Objects" },
    { emoji = "🔓"; name = "unlocked"; category = "Objects" },
    { emoji = "🚪"; name = "door"; category = "Objects" },
    { emoji = "🪞"; name = "mirror"; category = "Objects" },
    { emoji = "🪟"; name = "window"; category = "Objects" },
    { emoji = "🛋️"; name = "couch and lamp"; category = "Objects" },
    { emoji = "🪑"; name = "chair"; category = "Objects" },
    { emoji = "🚽"; name = "toilet"; category = "Objects" },
    { emoji = "🪠"; name = "plunger"; category = "Objects" },
    { emoji = "🚿"; name = "shower"; category = "Objects" },
    { emoji = "🛁"; name = "bathtub"; category = "Objects" },
    { emoji = "🪤"; name = "trap"; category = "Objects" },
    { emoji = "🧴"; name = "lotion bottle"; category = "Objects" },
    { emoji = "🧷"; name = "safety pin"; category = "Objects" },
    { emoji = "🧹"; name = "broom"; category = "Objects" },
    { emoji = "🧺"; name = "basket"; category = "Objects" },
    { emoji = "🧻"; name = "roll of paper"; category = "Objects" },
    { emoji = "🪣"; name = "bucket"; category = "Objects" },
    { emoji = "🧼"; name = "soap"; category = "Objects" },
    { emoji = "🫧"; name = "bubbles"; category = "Objects" },
    { emoji = "🪥"; name = "toothbrush"; category = "Objects" },
    { emoji = "🧽"; name = "sponge"; category = "Objects" },
    { emoji = "🪒"; name = "razor"; category = "Objects" },
    { emoji = "💈"; name = "barber pole"; category = "Objects" },
    { emoji = "🪭"; name = "folding hand fan"; category = "Objects" },
    { emoji = "📦"; name = "package"; category = "Objects" },
    { emoji = "✉️"; name = "envelope"; category = "Objects" },
    { emoji = "📧"; name = "email"; category = "Objects" },
    { emoji = "📨"; name = "incoming envelope"; category = "Objects" },
    { emoji = "📩"; name = "envelope with arrow"; category = "Objects" },
    { emoji = "📪"; name = "closed mailbox with lowered flag"; category = "Objects" },
    { emoji = "📫"; name = "closed mailbox with raised flag"; category = "Objects" },
    { emoji = "📬"; name = "open mailbox with raised flag"; category = "Objects" },
    { emoji = "📭"; name = "open mailbox with lowered flag"; category = "Objects" },
    { emoji = "📮"; name = "postbox"; category = "Objects" },
    { emoji = "📝"; name = "memo"; category = "Objects" },
    { emoji = "📄"; name = "page facing up"; category = "Objects" },
    { emoji = "📃"; name = "page with curl"; category = "Objects" },
    { emoji = "📑"; name = "bookmark tabs"; category = "Objects" },
    { emoji = "📊"; name = "bar chart"; category = "Objects" },
    { emoji = "📈"; name = "chart increasing"; category = "Objects" },
    { emoji = "📉"; name = "chart decreasing"; category = "Objects" },
    { emoji = "📋"; name = "clipboard"; category = "Objects" },
    { emoji = "📁"; name = "file folder"; category = "Objects" },
    { emoji = "📂"; name = "open file folder"; category = "Objects" },
    { emoji = "🗂️"; name = "card index dividers"; category = "Objects" },
    { emoji = "📅"; name = "calendar"; category = "Objects" },
    { emoji = "📆"; name = "tear-off calendar"; category = "Objects" },
    { emoji = "📇"; name = "card index"; category = "Objects" },
    { emoji = "📌"; name = "pushpin"; category = "Objects" },
    { emoji = "📍"; name = "round pushpin"; category = "Objects" },
    { emoji = "📎"; name = "paperclip"; category = "Objects" },
    { emoji = "🖇️"; name = "linked paperclips"; category = "Objects" },
    { emoji = "📏"; name = "straight ruler"; category = "Objects" },
    { emoji = "📐"; name = "triangular ruler"; category = "Objects" },
    { emoji = "✂️"; name = "scissors"; category = "Objects" },
    { emoji = "🗃️"; name = "card file box"; category = "Objects" },
    { emoji = "🗄️"; name = "file cabinet"; category = "Objects" },
    { emoji = "🗑️"; name = "wastebasket"; category = "Objects" },
    { emoji = "🔒"; name = "lock"; category = "Objects" },
    { emoji = "📖"; name = "open book"; category = "Objects" },
    { emoji = "📚"; name = "books"; category = "Objects" },
    { emoji = "📓"; name = "notebook"; category = "Objects" },
    { emoji = "📔"; name = "notebook with decorative cover"; category = "Objects" },
    { emoji = "📒"; name = "ledger"; category = "Objects" },
    { emoji = "📕"; name = "closed book"; category = "Objects" },
    { emoji = "📗"; name = "green book"; category = "Objects" },
    { emoji = "📘"; name = "blue book"; category = "Objects" },
    { emoji = "📙"; name = "orange book"; category = "Objects" },
    { emoji = "🔭"; name = "telescope"; category = "Objects" },
    { emoji = "🔬"; name = "microscope"; category = "Objects" },
    { emoji = "⚗️"; name = "alembic"; category = "Objects" },
    { emoji = "🩺"; name = "stethoscope"; category = "Objects" },
    { emoji = "💊"; name = "pill"; category = "Objects" },
    { emoji = "🩹"; name = "adhesive bandage"; category = "Objects" },
    { emoji = "🩼"; name = "crutch"; category = "Objects" },
    { emoji = "🩻"; name = "x-ray"; category = "Objects" },
    { emoji = "💉"; name = "syringe"; category = "Objects" },
    { emoji = "🩸"; name = "drop of blood"; category = "Objects" },
    // Symbols
    { emoji = "❤️"; name = "red heart"; category = "Symbols" },
    { emoji = "🧡"; name = "orange heart"; category = "Symbols" },
    { emoji = "💛"; name = "yellow heart"; category = "Symbols" },
    { emoji = "💚"; name = "green heart"; category = "Symbols" },
    { emoji = "💙"; name = "blue heart"; category = "Symbols" },
    { emoji = "💜"; name = "purple heart"; category = "Symbols" },
    { emoji = "🖤"; name = "black heart"; category = "Symbols" },
    { emoji = "🤍"; name = "white heart"; category = "Symbols" },
    { emoji = "🤎"; name = "brown heart"; category = "Symbols" },
    { emoji = "💔"; name = "broken heart"; category = "Symbols" },
    { emoji = "❣️"; name = "heart exclamation"; category = "Symbols" },
    { emoji = "💕"; name = "two hearts"; category = "Symbols" },
    { emoji = "💞"; name = "revolving hearts"; category = "Symbols" },
    { emoji = "💓"; name = "beating heart"; category = "Symbols" },
    { emoji = "💗"; name = "growing heart"; category = "Symbols" },
    { emoji = "💖"; name = "sparkling heart"; category = "Symbols" },
    { emoji = "💘"; name = "heart with arrow"; category = "Symbols" },
    { emoji = "💝"; name = "heart with ribbon"; category = "Symbols" },
    { emoji = "💟"; name = "heart decoration"; category = "Symbols" },
    { emoji = "☮️"; name = "peace symbol"; category = "Symbols" },
    { emoji = "✝️"; name = "latin cross"; category = "Symbols" },
    { emoji = "☪️"; name = "star and crescent"; category = "Symbols" },
    { emoji = "🔯"; name = "dotted six-pointed star"; category = "Symbols" },
    { emoji = "✡️"; name = "star of david"; category = "Symbols" },
    { emoji = "☸️"; name = "wheel of dharma"; category = "Symbols" },
    { emoji = "☯️"; name = "yin yang"; category = "Symbols" },
    { emoji = "🕎"; name = "menorah"; category = "Symbols" },
    { emoji = "🔱"; name = "trident emblem"; category = "Symbols" },
    { emoji = "📛"; name = "name badge"; category = "Symbols" },
    { emoji = "🔰"; name = "japanese symbol for beginner"; category = "Symbols" },
    { emoji = "⭕"; name = "hollow red circle"; category = "Symbols" },
    { emoji = "✅"; name = "check mark button"; category = "Symbols" },
    { emoji = "☑️"; name = "check box with check"; category = "Symbols" },
    { emoji = "✔️"; name = "check mark"; category = "Symbols" },
    { emoji = "❌"; name = "cross mark"; category = "Symbols" },
    { emoji = "❎"; name = "cross mark button"; category = "Symbols" },
    { emoji = "➕"; name = "plus sign"; category = "Symbols" },
    { emoji = "➖"; name = "minus sign"; category = "Symbols" },
    { emoji = "➗"; name = "division sign"; category = "Symbols" },
    { emoji = "✖️"; name = "multiplication sign"; category = "Symbols" },
    { emoji = "🔃"; name = "clockwise vertical arrows"; category = "Symbols" },
    { emoji = "🔄"; name = "counterclockwise arrows button"; category = "Symbols" },
    { emoji = "↩️"; name = "right arrow curving left"; category = "Symbols" },
    { emoji = "↪️"; name = "left arrow curving right"; category = "Symbols" },
    { emoji = "⤴️"; name = "right arrow curving up"; category = "Symbols" },
    { emoji = "⤵️"; name = "right arrow curving down"; category = "Symbols" },
    { emoji = "🔀"; name = "shuffle tracks button"; category = "Symbols" },
    { emoji = "🔁"; name = "repeat button"; category = "Symbols" },
    { emoji = "🔂"; name = "repeat single button"; category = "Symbols" },
    { emoji = "▶️"; name = "play button"; category = "Symbols" },
    { emoji = "⏩"; name = "fast-forward button"; category = "Symbols" },
    { emoji = "⏭️"; name = "next track button"; category = "Symbols" },
    { emoji = "⏯️"; name = "play or pause button"; category = "Symbols" },
    { emoji = "◀️"; name = "reverse button"; category = "Symbols" },
    { emoji = "⏪"; name = "fast reverse button"; category = "Symbols" },
    { emoji = "⏮️"; name = "last track button"; category = "Symbols" },
    { emoji = "🔔"; name = "bell"; category = "Symbols" },
    { emoji = "🔕"; name = "bell with slash"; category = "Symbols" },
    { emoji = "🔇"; name = "muted speaker"; category = "Symbols" },
    { emoji = "🔈"; name = "speaker low volume"; category = "Symbols" },
    { emoji = "🔉"; name = "speaker medium volume"; category = "Symbols" },
    { emoji = "🔊"; name = "speaker high volume"; category = "Symbols" },
    { emoji = "📢"; name = "loudspeaker"; category = "Symbols" },
    { emoji = "📣"; name = "megaphone"; category = "Symbols" },
    { emoji = "📯"; name = "postal horn"; category = "Symbols" },
    { emoji = "🔔"; name = "bell"; category = "Symbols" },
    { emoji = "⭐"; name = "star"; category = "Symbols" },
    { emoji = "🌟"; name = "glowing star"; category = "Symbols" },
    { emoji = "✨"; name = "sparkles"; category = "Symbols" },
    { emoji = "💫"; name = "dizzy"; category = "Symbols" },
    { emoji = "🔥"; name = "fire"; category = "Symbols" },
    { emoji = "💥"; name = "collision"; category = "Symbols" },
    { emoji = "❄️"; name = "snowflake"; category = "Symbols" },
    { emoji = "🌊"; name = "water wave"; category = "Symbols" },
    { emoji = "🌈"; name = "rainbow"; category = "Symbols" },
    { emoji = "☀️"; name = "sun"; category = "Symbols" },
    { emoji = "🌙"; name = "crescent moon"; category = "Symbols" },
    { emoji = "⚡"; name = "high voltage"; category = "Symbols" },
    { emoji = "🌀"; name = "cyclone"; category = "Symbols" },
    { emoji = "🎵"; name = "musical note"; category = "Symbols" },
    { emoji = "🎶"; name = "musical notes"; category = "Symbols" },
    { emoji = "💤"; name = "zzz"; category = "Symbols" },
    { emoji = "💯"; name = "hundred points"; category = "Symbols" },
    { emoji = "💢"; name = "anger symbol"; category = "Symbols" },
    { emoji = "💬"; name = "speech balloon"; category = "Symbols" },
    { emoji = "💭"; name = "thought balloon"; category = "Symbols" },
    { emoji = "💨"; name = "dashing away"; category = "Symbols" },
    { emoji = "🕳️"; name = "hole"; category = "Symbols" },
    { emoji = "💣"; name = "bomb"; category = "Symbols" },
    { emoji = "💬"; name = "speech bubble"; category = "Symbols" },
    { emoji = "🔞"; name = "no one under eighteen"; category = "Symbols" },
    { emoji = "📵"; name = "no mobile phones"; category = "Symbols" },
    { emoji = "🚫"; name = "prohibited"; category = "Symbols" },
    { emoji = "⛔"; name = "no entry"; category = "Symbols" },
    { emoji = "🚳"; name = "no bicycles"; category = "Symbols" },
    { emoji = "🚭"; name = "no smoking"; category = "Symbols" },
    { emoji = "♻️"; name = "recycling symbol"; category = "Symbols" },
    { emoji = "✴️"; name = "eight-pointed star"; category = "Symbols" },
    { emoji = "🔷"; name = "large blue diamond"; category = "Symbols" },
    { emoji = "🔶"; name = "large orange diamond"; category = "Symbols" },
    { emoji = "🔹"; name = "small blue diamond"; category = "Symbols" },
    { emoji = "🔸"; name = "small orange diamond"; category = "Symbols" },
    { emoji = "🔺"; name = "red triangle pointed up"; category = "Symbols" },
    { emoji = "🔻"; name = "red triangle pointed down"; category = "Symbols" },
    { emoji = "💠"; name = "diamond with a dot"; category = "Symbols" },
    { emoji = "🔘"; name = "radio button"; category = "Symbols" },
    { emoji = "🔲"; name = "black square button"; category = "Symbols" },
    { emoji = "🔳"; name = "white square button"; category = "Symbols" },
    { emoji = "⬛"; name = "black large square"; category = "Symbols" },
    { emoji = "⬜"; name = "white large square"; category = "Symbols" },
    { emoji = "🟥"; name = "red square"; category = "Symbols" },
    { emoji = "🟧"; name = "orange square"; category = "Symbols" },
    { emoji = "🟨"; name = "yellow square"; category = "Symbols" },
    { emoji = "🟩"; name = "green square"; category = "Symbols" },
    { emoji = "🟦"; name = "blue square"; category = "Symbols" },
    { emoji = "🟪"; name = "purple square"; category = "Symbols" },
    { emoji = "🟫"; name = "brown square"; category = "Symbols" },
    { emoji = "⚫"; name = "black circle"; category = "Symbols" },
    { emoji = "⚪"; name = "white circle"; category = "Symbols" },
    { emoji = "🔴"; name = "red circle"; category = "Symbols" },
    { emoji = "🟠"; name = "orange circle"; category = "Symbols" },
    { emoji = "🟡"; name = "yellow circle"; category = "Symbols" },
    { emoji = "🟢"; name = "green circle"; category = "Symbols" },
    { emoji = "🔵"; name = "blue circle"; category = "Symbols" },
    { emoji = "🟣"; name = "purple circle"; category = "Symbols" },
    { emoji = "🟤"; name = "brown circle"; category = "Symbols" },
    // Flags
    { emoji = "🇺🇸"; name = "united states flag"; category = "Flags" },
    { emoji = "🇬🇧"; name = "united kingdom flag"; category = "Flags" },
    { emoji = "🇨🇦"; name = "canada flag"; category = "Flags" },
    { emoji = "🇦🇺"; name = "australia flag"; category = "Flags" },
    { emoji = "🇫🇷"; name = "france flag"; category = "Flags" },
    { emoji = "🇩🇪"; name = "germany flag"; category = "Flags" },
    { emoji = "🇮🇹"; name = "italy flag"; category = "Flags" },
    { emoji = "🇪🇸"; name = "spain flag"; category = "Flags" },
    { emoji = "🇯🇵"; name = "japan flag"; category = "Flags" },
    { emoji = "🇨🇳"; name = "china flag"; category = "Flags" },
    { emoji = "🇰🇷"; name = "south korea flag"; category = "Flags" },
    { emoji = "🇷🇺"; name = "russia flag"; category = "Flags" },
    { emoji = "🇮🇳"; name = "india flag"; category = "Flags" },
    { emoji = "🇧🇷"; name = "brazil flag"; category = "Flags" },
    { emoji = "🇲🇽"; name = "mexico flag"; category = "Flags" },
    { emoji = "🇿🇦"; name = "south africa flag"; category = "Flags" },
    { emoji = "🇸🇪"; name = "sweden flag"; category = "Flags" },
    { emoji = "🇳🇴"; name = "norway flag"; category = "Flags" },
    { emoji = "🇩🇰"; name = "denmark flag"; category = "Flags" },
    { emoji = "🇫🇮"; name = "finland flag"; category = "Flags" },
    { emoji = "🇳🇱"; name = "netherlands flag"; category = "Flags" },
    { emoji = "🇧🇪"; name = "belgium flag"; category = "Flags" },
    { emoji = "🇨🇭"; name = "switzerland flag"; category = "Flags" },
    { emoji = "🇦🇹"; name = "austria flag"; category = "Flags" },
    { emoji = "🇬🇷"; name = "greece flag"; category = "Flags" },
    { emoji = "🇹🇷"; name = "turkey flag"; category = "Flags" },
    { emoji = "🇸🇦"; name = "saudi arabia flag"; category = "Flags" },
    { emoji = "🇮🇱"; name = "israel flag"; category = "Flags" },
    { emoji = "🇪🇬"; name = "egypt flag"; category = "Flags" },
    { emoji = "🇳🇬"; name = "nigeria flag"; category = "Flags" },
    { emoji = "🇰🇪"; name = "kenya flag"; category = "Flags" },
    { emoji = "🇬🇭"; name = "ghana flag"; category = "Flags" },
    { emoji = "🇪🇹"; name = "ethiopia flag"; category = "Flags" },
    { emoji = "🇹🇿"; name = "tanzania flag"; category = "Flags" },
    { emoji = "🇺🇬"; name = "uganda flag"; category = "Flags" },
    { emoji = "🇲🇦"; name = "morocco flag"; category = "Flags" },
    { emoji = "🇹🇳"; name = "tunisia flag"; category = "Flags" },
    { emoji = "🇱🇾"; name = "libya flag"; category = "Flags" },
    { emoji = "🇩🇿"; name = "algeria flag"; category = "Flags" },
    { emoji = "🇦🇷"; name = "argentina flag"; category = "Flags" },
    { emoji = "🇨🇱"; name = "chile flag"; category = "Flags" },
    { emoji = "🇨🇴"; name = "colombia flag"; category = "Flags" },
    { emoji = "🇵🇪"; name = "peru flag"; category = "Flags" },
    { emoji = "🇻🇪"; name = "venezuela flag"; category = "Flags" },
    { emoji = "🇪🇨"; name = "ecuador flag"; category = "Flags" },
    { emoji = "🇧🇴"; name = "bolivia flag"; category = "Flags" },
    { emoji = "🇺🇾"; name = "uruguay flag"; category = "Flags" },
    { emoji = "🇵🇾"; name = "paraguay flag"; category = "Flags" },
    { emoji = "🇵🇱"; name = "poland flag"; category = "Flags" },
    { emoji = "🇵🇹"; name = "portugal flag"; category = "Flags" },
    { emoji = "🇵🇭"; name = "philippines flag"; category = "Flags" },
    { emoji = "🇮🇩"; name = "indonesia flag"; category = "Flags" },
    { emoji = "🇲🇾"; name = "malaysia flag"; category = "Flags" },
    { emoji = "🇸🇬"; name = "singapore flag"; category = "Flags" },
    { emoji = "🇹🇭"; name = "thailand flag"; category = "Flags" },
    { emoji = "🇻🇳"; name = "vietnam flag"; category = "Flags" },
    { emoji = "🇵🇰"; name = "pakistan flag"; category = "Flags" },
    { emoji = "🇧🇩"; name = "bangladesh flag"; category = "Flags" },
    { emoji = "🇺🇦"; name = "ukraine flag"; category = "Flags" },
    { emoji = "🇷🇴"; name = "romania flag"; category = "Flags" },
    { emoji = "🇭🇺"; name = "hungary flag"; category = "Flags" },
    { emoji = "🇨🇿"; name = "czech republic flag"; category = "Flags" },
    { emoji = "🇧🇬"; name = "bulgaria flag"; category = "Flags" },
    { emoji = "🇭🇷"; name = "croatia flag"; category = "Flags" },
    { emoji = "🇸🇰"; name = "slovakia flag"; category = "Flags" },
    { emoji = "🇸🇮"; name = "slovenia flag"; category = "Flags" },
    { emoji = "🇷🇸"; name = "serbia flag"; category = "Flags" },
    { emoji = "🇧🇦"; name = "bosnia flag"; category = "Flags" },
    { emoji = "🇦🇱"; name = "albania flag"; category = "Flags" },
    { emoji = "🇲🇰"; name = "north macedonia flag"; category = "Flags" },
    { emoji = "🇮🇷"; name = "iran flag"; category = "Flags" },
    { emoji = "🇮🇶"; name = "iraq flag"; category = "Flags" },
    { emoji = "🇸🇾"; name = "syria flag"; category = "Flags" },
    { emoji = "🇯🇴"; name = "jordan flag"; category = "Flags" },
    { emoji = "🇱🇧"; name = "lebanon flag"; category = "Flags" },
    { emoji = "🇰🇼"; name = "kuwait flag"; category = "Flags" },
    { emoji = "🇦🇪"; name = "united arab emirates flag"; category = "Flags" },
    { emoji = "🇶🇦"; name = "qatar flag"; category = "Flags" },
    { emoji = "🇧🇭"; name = "bahrain flag"; category = "Flags" },
    { emoji = "🇴🇲"; name = "oman flag"; category = "Flags" },
    { emoji = "🇾🇪"; name = "yemen flag"; category = "Flags" },
    { emoji = "🇳🇿"; name = "new zealand flag"; category = "Flags" },
    { emoji = "🇵🇬"; name = "papua new guinea flag"; category = "Flags" },
    { emoji = "🇫🇯"; name = "fiji flag"; category = "Flags" },
    { emoji = "🇷🇼"; name = "rwanda flag"; category = "Flags" },
    { emoji = "🇿🇼"; name = "zimbabwe flag"; category = "Flags" },
    { emoji = "🇨🇲"; name = "cameroon flag"; category = "Flags" },
    { emoji = "🇨🇩"; name = "dr congo flag"; category = "Flags" },
    { emoji = "🇲🇿"; name = "mozambique flag"; category = "Flags" },
    { emoji = "🇦🇴"; name = "angola flag"; category = "Flags" },
    { emoji = "🏳️"; name = "white flag"; category = "Flags" },
    { emoji = "🏴"; name = "black flag"; category = "Flags" },
    { emoji = "🏁"; name = "chequered flag"; category = "Flags" },
    { emoji = "🚩"; name = "triangular flag"; category = "Flags" },
    { emoji = "🌈"; name = "rainbow flag"; category = "Flags" },
  ];

  let categories : [Text] = [
    "Smileys & Emotion",
    "People & Body",
    "Animals & Nature",
    "Food & Drink",
    "Travel & Places",
    "Activities & Sports",
    "Objects",
    "Symbols",
    "Flags",
  ];

  public query ({ caller }) func getCategories() : async [Text] {
    categories;
  };

  public query ({ caller }) func getEmojisByCategory(category : Text) : async [Emoji] {
    emojis.filter(func(e) { e.category == category });
  };

  public query ({ caller }) func searchEmojis(queryText : Text) : async [Emoji] {
    let lowerQuery = queryText.toLower();
    emojis.filter(
      func(e) {
        e.name.toLower().contains(#text lowerQuery);
      }
    );
  };
};
