/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Emoji = IDL.Record({
  'name' : IDL.Text,
  'emoji' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getEmojisByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Emoji)], ['query']),
  'searchEmojis' : IDL.Func([IDL.Text], [IDL.Vec(Emoji)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Emoji = IDL.Record({
    'name' : IDL.Text,
    'emoji' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getEmojisByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Emoji)], ['query']),
    'searchEmojis' : IDL.Func([IDL.Text], [IDL.Vec(Emoji)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };